//@version=5
indicator(shorttitle="BB_break MTF", title="Bollinger Bands Break MTF", timeframe = "" ,overlay=true)
n = input.int(20, minval=1)
source = input(close, title="Source")
mult = input.float(3.0, minval=0.001, maxval=50, title="StdDev")
break_sum(x, y,isHour) =>
    sum = 0.0
    for i = isHour to y + isHour - 2
        sum := sum + x[i] / (y-1)
    sum
pow_sum(x, y,isHour) =>
    sum = 0.0
    for i = isHour to y + isHour - 2
        sum := sum + math.pow(x[i],2)
    sum
    
A = n - 1 - math.pow(mult, 2)

basis = timeframe.period == "60"? break_sum(source, n,1):timeframe.isintraday ? request.security(syminfo.tickerid,"60",break_sum(source, n,0)):break_sum(source, n,1)
Sn = basis * (n-1)
Hn = timeframe.period == "60"? pow_sum(source, n,1):timeframe.isintraday ? request.security(syminfo.tickerid,"60",pow_sum(source, n,0)):pow_sum(source, n,1)
dev2 = n*((n-1)*Hn-math.pow(Sn,2))/A
dev = mult*math.sqrt(dev2)/(n-1)
upper = basis + dev
lower = basis - dev
offset = timeframe.period == "60"? 0:timeframe.isintraday ? 1:0
p1 = plot(upper, "Upper", color=#ff0000, offset = offset)
p2 = plot(lower, "Lower", color=#ff0000, offset = offset)
p3 = plot(basis, "Basis",offset = offset)
