//@version=5
indicator(shorttitle="BB_break MTF Select", title="Bollinger Bands Break MTF Select Timeframe" ,overlay=true)
n = input.int(20, minval=1)

source = input(close, title="Source")
mult = input.float(3.0, minval=0.001, maxval=50, title="StdDev")
string TIME = input.timeframe(title="Time Frame",  defval="60")

break_sum(x, y,isHour) =>
    sum = 0.0
    for i = isHour to y + isHour - 2
        sum := sum + x[i] / (y-1)
    sum
pow_sum(x, y,isHour) =>
    sum = 0.0
    for i = isHour to y + isHour - 2
        sum := sum + math.pow(x[i],2)
    sum
    
A = n - 1 - math.pow(mult, 2)

m = not barstate.islast?0:1
basis = timeframe.period == TIME? break_sum(source, n,1):request.security(syminfo.tickerid,TIME,break_sum(source, n,m))
Sn = basis * (n-1)
Hn = timeframe.period == TIME? pow_sum(source, n,1):request.security(syminfo.tickerid,TIME,pow_sum(source, n,m))
dev2 = n*((n-1)*Hn-math.pow(Sn,2))/A
dev = mult*math.sqrt(dev2)/(n-1)
upper = basis + dev
lower = basis - dev

offset = barstate.islast and timeframe.period==TIME?0:1
p1 = plot(upper, "Upper", color=#ff0000, offset = offset)
p2 = plot(lower, "Lower", color=#ff0000, offset = offset)
p3 = plot(basis, "Basis",offset = offset)